# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app_main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 300)
        MainWindow.setMinimumSize(QtCore.QSize(600, 300))
        MainWindow.setMaximumSize(QtCore.QSize(600, 300))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 4, 1, 1, 1)
        self.word_to_pdf_option = QtWidgets.QRadioButton(self.centralwidget)
        self.word_to_pdf_option.setObjectName("word_to_pdf_option")
        self.gridLayout.addWidget(self.word_to_pdf_option, 1, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 1, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 0, 1, 1, 1)
        self.pdf_merger_option = QtWidgets.QRadioButton(self.centralwidget)
        self.pdf_merger_option.setObjectName("pdf_merger_option")
        self.gridLayout.addWidget(self.pdf_merger_option, 3, 1, 1, 1)
        self.proceed_button = QtWidgets.QPushButton(self.centralwidget)
        self.proceed_button.setObjectName("proceed_button")
        self.gridLayout.addWidget(self.proceed_button, 5, 1, 1, 1)
        self.pdf_to_word_button = QtWidgets.QRadioButton(self.centralwidget)
        self.pdf_to_word_button.setObjectName("pdf_to_word_button")
        self.gridLayout.addWidget(self.pdf_to_word_button, 2, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Document Converter"))
        self.word_to_pdf_option.setText(_translate("MainWindow", "Word Document to PDF"))
        self.pdf_merger_option.setText(_translate("MainWindow", "PDF Merger"))
        self.proceed_button.setText(_translate("MainWindow", "Proceed"))
        self.pdf_to_word_button.setText(_translate("MainWindow", "PDF to Word Document"))
