# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pdf_merger.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PDFMerger(object):
    def setupUi(self, PDFMerger):
        PDFMerger.setObjectName("PDFMerger")
        PDFMerger.resize(600, 250)
        PDFMerger.setMinimumSize(QtCore.QSize(600, 250))
        PDFMerger.setMaximumSize(QtCore.QSize(600, 250))
        self.gridLayoutWidget = QtWidgets.QWidget(PDFMerger)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 0, 561, 241))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 4, 3, 1, 1)
        self.proceed_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.proceed_button.setObjectName("proceed_button")
        self.gridLayout.addWidget(self.proceed_button, 4, 2, 1, 1)
        self.output_browse_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.output_browse_button.setObjectName("output_browse_button")
        self.gridLayout.addWidget(self.output_browse_button, 2, 4, 1, 1)
        self.input_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.input_label.setObjectName("input_label")
        self.gridLayout.addWidget(self.input_label, 1, 0, 1, 1)
        self.input_browse_button = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.input_browse_button.setObjectName("input_browse_button")
        self.gridLayout.addWidget(self.input_browse_button, 1, 4, 1, 1)
        self.output_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.output_label.setObjectName("output_label")
        self.gridLayout.addWidget(self.output_label, 2, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 4, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 3, 1, 1, 3)
        self.output_line_edit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.output_line_edit.setReadOnly(True)
        self.output_line_edit.setObjectName("output_line_edit")
        self.gridLayout.addWidget(self.output_line_edit, 2, 1, 1, 3)
        self.input_line_edit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.input_line_edit.setReadOnly(True)
        self.input_line_edit.setObjectName("input_line_edit")
        self.gridLayout.addWidget(self.input_line_edit, 1, 1, 1, 3)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 0, 1, 1, 3)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem4, 5, 1, 1, 3)

        self.retranslateUi(PDFMerger)
        QtCore.QMetaObject.connectSlotsByName(PDFMerger)

    def retranslateUi(self, PDFMerger):
        _translate = QtCore.QCoreApplication.translate
        PDFMerger.setWindowTitle(_translate("PDFMerger", "PDF Merger"))
        self.proceed_button.setText(_translate("PDFMerger", "Proceed"))
        self.output_browse_button.setText(_translate("PDFMerger", "Browse"))
        self.input_label.setText(_translate("PDFMerger", "Select PDF Files:"))
        self.input_browse_button.setText(_translate("PDFMerger", "Browse"))
        self.output_label.setText(_translate("PDFMerger", "Output File: "))
