# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'word_to_pdf.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WordToPDF(object):
    def setupUi(self, WordToPDF):
        WordToPDF.setObjectName("WordToPDF")
        WordToPDF.setWindowModality(QtCore.Qt.WindowModal)
        WordToPDF.resize(450, 250)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(WordToPDF.sizePolicy().hasHeightForWidth())
        WordToPDF.setSizePolicy(sizePolicy)
        WordToPDF.setMinimumSize(QtCore.QSize(450, 250))
        WordToPDF.setMaximumSize(QtCore.QSize(450, 250))
        self.verticalLayout = QtWidgets.QVBoxLayout(WordToPDF)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.input_label = QtWidgets.QLabel(WordToPDF)
        self.input_label.setObjectName("input_label")
        self.gridLayout_2.addWidget(self.input_label, 1, 0, 1, 1)
        self.output_label = QtWidgets.QLabel(WordToPDF)
        self.output_label.setObjectName("output_label")
        self.gridLayout_2.addWidget(self.output_label, 2, 0, 1, 1)
        self.browse_input_button = QtWidgets.QPushButton(WordToPDF)
        self.browse_input_button.setObjectName("browse_input_button")
        self.gridLayout_2.addWidget(self.browse_input_button, 1, 2, 1, 1)
        self.input_line_edit = QtWidgets.QLineEdit(WordToPDF)
        self.input_line_edit.setReadOnly(True)
        self.input_line_edit.setObjectName("input_line_edit")
        self.gridLayout_2.addWidget(self.input_line_edit, 1, 1, 1, 1)
        self.title_label = QtWidgets.QLabel(WordToPDF)
        self.title_label.setAlignment(QtCore.Qt.AlignCenter)
        self.title_label.setObjectName("title_label")
        self.gridLayout_2.addWidget(self.title_label, 0, 0, 1, 3)
        self.output_line_edit = QtWidgets.QLineEdit(WordToPDF)
        self.output_line_edit.setReadOnly(True)
        self.output_line_edit.setObjectName("output_line_edit")
        self.gridLayout_2.addWidget(self.output_line_edit, 2, 1, 1, 1)
        self.browse_output_button = QtWidgets.QPushButton(WordToPDF)
        self.browse_output_button.setObjectName("browse_output_button")
        self.gridLayout_2.addWidget(self.browse_output_button, 2, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 0, 1, 1)
        self.convert_button = QtWidgets.QPushButton(WordToPDF)
        self.convert_button.setObjectName("convert_button")
        self.gridLayout.addWidget(self.convert_button, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)

        self.retranslateUi(WordToPDF)
        QtCore.QMetaObject.connectSlotsByName(WordToPDF)

    def retranslateUi(self, WordToPDF):
        _translate = QtCore.QCoreApplication.translate
        WordToPDF.setWindowTitle(_translate("WordToPDF", "Document Converter"))
        self.input_label.setText(_translate("WordToPDF", "Input File: "))
        self.output_label.setText(_translate("WordToPDF", "Output File: "))
        self.browse_input_button.setText(_translate("WordToPDF", "Browse"))
        self.title_label.setText(_translate("WordToPDF", "Word Document to PDF File"))
        self.browse_output_button.setText(_translate("WordToPDF", "Browse"))
        self.convert_button.setText(_translate("WordToPDF", "Convert"))
